version: '3'

volumes:
  pg_data:
  static:
  media:  # Загруженные пользователями картинки

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - media:/app/media # Сохраняем загрузки пользователей
    depends_on:
      - db # Ждем запуска БД

  frontend:
    env_file: .env
    build: ./frontend/
    # Собираем проект, копируем готовые файлы в том 'static'
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80 # Основной порт доступа к приложению
    volumes:
      - static:/static # Раздаем фронтенд
      - media:/app/media # Раздаем медиа
    depends_on:
      - backend # Ждем запуска API